
# medical_keywords.py
medical_keywords = [
    # Medical Conditions
    "abdominal pain", "abscess", "acne", "acute", "addiction", "ADHD", "allergy", "alopecia",
    "Alzheimer's", "anemia", "aneurysm", "angina", "anorexia", "anxiety", "arthritis",
    "asthma", "atherosclerosis", "autism", "autoimmune", "back pain", "bacterial infection",
    "bipolar disorder", "bladder infection", "bleeding", "blindness", "blood pressure",
    "bone fracture", "brain tumor", "breast cancer", "bronchitis", "burn", "cancer",
    "carpal tunnel", "cataract", "celiac disease", "cerebral palsy", "chickenpox",
    "chlamydia", "cholesterol", "chronic fatigue", "cirrhosis", "colitis", "colon cancer",
    "concussion", "congenital", "COPD", "coronary artery disease", "Crohn's disease",
    "cystic fibrosis", "dandruff", "deafness", "dehydration", "dementia", "depression",
    "dermatitis", "diabetes", "diarrhea", "dizziness", "Down syndrome", "dry eye",
    "dyslexia", "eczema", "edema", "endometriosis", "epilepsy", "erectile dysfunction",
    "fibromyalgia", "flu", "fracture", "gallstones", "gastritis", "GERD", "glaucoma",
    "gout", "hair loss", "headache", "hearing loss", "heart attack", "heart disease",
    "heart failure", "hepatitis", "herpes", "HIV", "hypertension", "hyperthyroidism",
    "hypothyroidism", "IBS", "infection", "infertility", "influenza", "insomnia",
    "iron deficiency", "jaundice", "kidney disease", "kidney stone", "knee pain",
    "lactose intolerance", "liver disease", "lung cancer", "lymphoma", "malaria",
    "measles", "melanoma", "meningitis", "migraine", "miscarriage", "MRSA", "multiple sclerosis",
    "muscle strain", "myocardial infarction", "nausea", "nephritis", "neuropathy",
    "obesity", "osteoporosis", "ovarian cancer", "pancreatitis", "parkinson's disease",
    "PCOS", "peptic ulcer", "pneumonia", "pregnancy", "prostate cancer", "psoriasis",
    "PTSD", "rabies", "rheumatoid arthritis", "rosacea", "schizophrenia", "scoliosis",
    "sepsis", "sinusitis", "skin cancer", "sleep apnea", "STD", "stomach ulcer", "stroke",
    "syphilis", "tendonitis", "testicular cancer", "tuberculosis", "type 1 diabetes",
    "type 2 diabetes", "ulcerative colitis", "UTI", "varicose veins", "vertigo",
    "vitamin deficiency", "vomiting", "warts", "whiplash", "whooping cough", "yeast infection",
    "zika virus",

    # Medications
    "acetaminophen", "acyclovir", "adrenaline", "albuterol", "alprazolam", "amiodarone",
    "amitriptyline", "amlodipine", "amoxicillin", "ampicillin", "anastrozole", "antibiotic",
    "antidepressant", "antihistamine", "aspirin", "atenolol", "atorvastatin", "azithromycin",
    "baclofen", "beclomethasone", "benzodiazepine", "betamethasone", "bisoprolol",
    "budesonide", "buprenorphine", "bupropion", "carbamazepine", "carvedilol", "celecoxib",
    "cephalexin", "ciprofloxacin", "citalopram", "clindamycin", "clonazepam", "clonidine",
    "clopidogrel", "codeine", "colchicine", "cyclobenzaprine", "dexamethasone", "diclofenac",
    "diltiazem", "diphenhydramine", "duloxetine", "enalapril", "epinephrine", "esomeprazole",
    "estradiol", "fentanyl", "fluoxetine", "fluticasone", "furosemide", "gabapentin",
    "gemfibrozil", "glimepiride", "glyburide", "guaifenesin", "haloperidol", "heparin",
    "hydrochlorothiazide", "hydrocodone", "hydroxyzine", "ibuprofen", "insulin", "isosorbide",
    "ketoconazole", "labetalol", "lamotrigine", "lansoprazole", "levetiracetam", "levofloxacin",
    "levothyroxine", "lidocaine", "lisinopril", "loratadine", "lorazepam", "losartan",
    "lovastatin", "meclizine", "meloxicam", "metformin", "methotrexate", "methylprednisolone",
    "metoprolol", "metronidazole", "morphine", "naproxen", "nifedipine", "nitroglycerin",
    "nortriptyline", "olanzapine", "omeprazole", "ondansetron", "oxycodone", "pantoprazole",
    "paroxetine", "penicillin", "phenytoin", "pioglitazone", "pravastatin", "prednisone",
    "propranolol", "quetiapine", "ranitidine", "sertraline", "sildenafil", "simvastatin",
    "spironolactone", "sulfamethoxazole", "sumatriptan", "tadalafil", "tamoxifen",
    "temazepam", "tramadol", "trazodone", "valacyclovir", "valsartan", "venlafaxine",
    "verapamil", "warfarin", "zolpidem",

    # Procedures and Treatments
    "ablation", "amputation", "angiography", "angioplasty", "antibiotic therapy",
    "appendectomy", "arthroscopy", "bariatric surgery", "biopsy", "blood transfusion",
    "bone marrow transplant", "bronchoscopy", "bypass surgery", "cardiac catheterization",
    "carotid endarterectomy", "C-section", "chemotherapy", "cholecystectomy", "colonoscopy",
    "coronary angioplasty", "CT scan", "dialysis", "echocardiogram", "electrocardiogram",
    "electroencephalogram", "endoscopy", "gastrectomy", "gastroscopy", "hemodialysis",
    "hernia repair", "hysterectomy", "immunotherapy", "IVF", "knee replacement",
    "liver transplant", "lumbar puncture", "mammography", "mastectomy", "MRI", "neurosurgery",
    "organ transplant", "pacemaker", "pap smear", "PET scan", "physical therapy", "radiation therapy",
    "renal dialysis", "spinal fusion", "stent placement", "steroids", "thoracotomy",
    "ultrasound", "vaccination", "vasectomy", "x-ray",

    # Specialties
    "allergy and immunology", "anesthesiology", "cardiology", "dermatology", "emergency medicine",
    "endocrinology", "family medicine", "gastroenterology", "geriatrics", "gynecology",
    "hematology", "infectious disease", "internal medicine", "nephrology", "neurology",
    "neurosurgery", "obstetrics", "oncology", "ophthalmology", "orthopedic surgery",
    "otolaryngology", "pediatrics", "plastic surgery", "psychiatry", "pulmonology",
    "radiology", "rheumatology", "urology",

    # Body Systems and Anatomy
    "cardiovascular system", "circulatory system", "digestive system", "endocrine system",
    "immune system", "lymphatic system", "muscular system", "nervous system", "reproductive system",
    "respiratory system", "skeletal system", "skin", "urinary system", "abdomen", "artery",
    "bone", "brain", "colon", "eye", "heart", "intestine", "joint", "kidney", "liver",
    "lung", "muscle", "nerve", "pancreas", "spinal cord", "stomach", "tendon", "testes",
    "thyroid", "uterus", "vein",

    # Medical Equipment
    "catheter", "defibrillator", "endoscope", "glucose meter", "hearing aid", "incubator",
    "IV pump", "MRI machine", "pacemaker", "scalpel", "stethoscope", "syringe", "thermometer",
    "ultrasound machine", "ventilator", "wheelchair", "x-ray machine",

    # Medical Terminology
    "acute", "benign", "biopsy", "chronic", "diagnosis", "edema", "epidemiology", "etiology",
    "idiopathic", "inflammation", "lesion", "malignant", "metastasis", "pathogen", "prognosis",
    "remission", "sepsis", "syndrome", "tumor", "viral", "vital signs",

    # Medical Research
    "clinical trial", "double-blind study", "epidemiological study", "meta-analysis",
    "placebo", "randomized controlled trial", "systematic review",

    # Public Health
    "epidemiology", "health promotion", "immunization", "infectious disease control",
    "pandemic", "public health policy", "quarantine", "vaccination program",

    # Miscellaneous
    "addiction medicine", "alternative medicine", "biomedical ethics", "evidence-based medicine",
    "healthcare administration", "medical education", "preventive medicine"

    # medical_keywords.py

    "health", "medicine", "medical", "doctor", "symptom", "treatment", "disease",
    "illness", "condition", "therapy", "surgery", "diagnosis", "prescription",
    "vaccine", "infection", "virus", "bacteria", "mental health", "cardiology",
    "neurology", "oncology", "orthopedic", "dermatology", "pediatric", "gynecology",
    "pharmacy", "immunology", "pathology", "radiology", "anatomy", "physiology",
    "biochemistry", "pharmacology", "hematology", "gastroenterology", "endocrinology",
    "nephrology", "pulmonology", "rheumatology", "urology", "otolaryngology",
    "ophthalmology", "psychiatry", "dentistry", "nutrition", "public health",
    "epidemiology", "chronic", "acute", "emergency", "first aid", "general practice",
    "family medicine", "internal medicine", "primary care", "specialist", "surgeon",
    "anesthesiology", "orthodontics", "podiatry", "nursing", "midwifery", "genetics",
    "toxicology", "dermatitis", "arthritis", "diabetes", "hypertension", "cholesterol",
    "obesity", "allergy", "asthma", "flu", "cold", "COVID-19", "pandemic", "epidemic",
    "cardiovascular", "stroke", "blood pressure", "infection control", "osteoporosis",
    "reproductive health", "menopause", "pregnancy", "childbirth", "infant care",
    "pediatrics", "geriatrics", "HIV", "AIDS", "hepatitis", "malaria", "tuberculosis",
    "autoimmune", "cancer", "tumor", "biopsy", "MRI", "CT scan", "X-ray", "ultrasound",
    "vaccination", "immunization", "antibiotic", "antiviral", "pain management",
    "opioid", "rehabilitation", "physical therapy", "occupational therapy",
    "speech therapy", "cognitive therapy", "behavioral therapy", "psychotherapy",
    "counseling", "support group", "dietitian", "nutritionist", "exercise",
    "wellness", "preventive care", "screening", "checkup", "imaging", "blood test",
    "lab work", "genome", "DNA", "RNA", "genetic testing", "telemedicine",
    "homeopathy", "naturopathy", "acupuncture", "chiropractic", "herbal medicine",
    "alternative medicine", "integrative medicine", "holistic medicine", "palliative care",
    "hospice", "end-of-life care", "organ donation", "transplant", "fertility",
    "IVF", "contraception", "birth control", "STI", "STD", "menstruation", "PMS",
    "PCOS", "endometriosis", "erectile dysfunction", "prostate health", "urologist",
    "bariatric surgery", "weight loss", "smoking cessation", "alcohol dependency",
    "drug rehabilitation", "eating disorder", "anorexia", "bulimia", "binge eating",
    "sleep disorder", "insomnia", "sleep apnea", "narcolepsy", "restless legs syndrome",
    "chronic fatigue syndrome", "fibromyalgia", "migraine", "headache", "back pain",
    "neck pain", "joint pain", "musculoskeletal", "sports injury", "trauma",
    "burns", "wound care", "fracture", "dislocation", "sprain", "strain",
    "hernia", "appendicitis", "gallstones", "kidney stones", "urinary tract infection",
    "bladder infection", "cystitis", "pyelonephritis", "prostatitis", "meningitis",
    "encephalitis", "sepsis", "blood poisoning", "toxin exposure", "chemical burn",
    "radiation exposure", "biological hazard", "occupational health", "environmental health",
    "workplace safety", "industrial hygiene", "ergonomics", "hazardous materials",
    "infectious waste", "sanitation", "hygiene", "vaccination program", "immunotherapy",
    "biologics", "monoclonal antibodies", "gene therapy", "stem cell therapy",
    "regenerative medicine", "3D printing", "prosthetics", "orthotics", "assistive technology",
    "hearing aid", "cochlear implant", "visual impairment", "low vision", "blindness",
    "deafness", "speech impairment", "language disorder", "communication disorder",
    "learning disability", "autism", "ADHD", "developmental delay", "cognitive impairment",
    "intellectual disability", "Down syndrome", "cerebral palsy", "muscular dystrophy",
    "spina bifida", "hydrocephalus", "congenital heart defect", "cleft lip", "cleft palate",
    "sickle cell anemia", "thalassemia", "hemophilia", "von Willebrand disease",
    "lymphoma", "leukemia", "myeloma", "melanoma", "basal cell carcinoma",
    "squamous cell carcinoma", "breast cancer", "lung cancer", "prostate cancer",
    "colorectal cancer", "pancreatic cancer", "liver cancer", "kidney cancer",
    "bladder cancer", "ovarian cancer", "uterine cancer", "cervical cancer",
    "testicular cancer", "bone cancer", "sarcoma", "neuroblastoma", "retinoblastoma",
    "Wilms tumor", "Ewing sarcoma", "rhabdomyosarcoma", "thyroid cancer",
    "parathyroid cancer", "adrenal cancer", "pituitary tumor", "neuroendocrine tumor",
    "carcinoid tumor", "pheochromocytoma", "merkel cell carcinoma", "Kaposi sarcoma",
    "mesothelioma", "pleural effusion", "ascites", "pericardial effusion",
    "lymphedema", "angiogenesis inhibitor", "checkpoint inhibitor", "CAR-T therapy",
    "radiation therapy", "brachytherapy", "radioisotope therapy", "proton therapy",
    "cyberknife", "gamma knife", "laser therapy", "cryotherapy", "hyperthermia",
    "photodynamic therapy", "electroporation", "gene editing", "CRISPR", "base editing",
    "prime editing", "transgenic", "knockout mouse", "xenograft", "organoid",
    "lab on a chip", "organ on a chip", "microfluidics", "bioprinting",
    "biosensor", "bioinformatics", "biostatistics", "epigenetics", "proteomics",
    "metabolomics", "glycomics", "lipidomics", "pharmacogenomics", "nutrigenomics",
    "toxicogenomics", "precision medicine", "personalized medicine", "systems biology",
    "synthetic biology", "computational biology", "molecular modeling", "drug design",
    "high throughput screening", "virtual screening", "molecular docking",
    "structure based drug design", "fragment based drug design", "de novo drug design",
    "lead optimization", "preclinical research", "clinical trial", "phase I",
    "phase II", "phase III", "phase IV", "investigational new drug", "new drug application",
    "biologics license application", "orphan drug", "fast track", "breakthrough therapy",
    "accelerated approval", "priority review", "compassionate use", "expanded access",
    "right to try", "clinical endpoint", "surrogate endpoint", "biomarker", "diagnostic",
    "prognostic", "predictive", "theranostic", "companion diagnostic", "risk factor",
    "preventive measure", "public health intervention", "health policy", "health economics",
    "healthcare management", "healthcare administration", "health informatics",
    "electronic health record", "personal health record", "health information exchange",
    "telehealth", "mhealth", "ehealth", "digital health", "health literacy",
    "patient engagement", "patient empowerment", "shared decision making",
    "patient centered care", "care coordination", "integrated care", "accountable care",
    "population health", "community health", "global health", "health disparity",
    "health equity", "social determinant of health", "health impact assessment",
    "health promotion", "disease prevention", "wellness program", "fitness program",
    "worksite wellness", "community outreach", "patient advocacy", "health education",
    "behavior change", "motivational interviewing", "cognitive behavioral therapy",
    "acceptance and commitment therapy", "mindfulness based stress reduction",
    "mindfulness based cognitive therapy", "dialectical behavior therapy",
    "solution focused therapy", "narrative therapy", "family therapy", "couples therapy",
    "group therapy", "support group", "self help group", "peer support", "mental health first aid",
    "crisis intervention", "suicide prevention", "trauma informed care", "resilience training",
    "stress management", "anger management", "conflict resolution", "communication skills",
    "life skills", "social skills", "emotional intelligence", "positive psychology",
    "well being", "quality of life", "life satisfaction", "happiness", "gratitude",
    "mindfulness", "meditation", "yoga", "tai chi", "qigong", "relaxation techniques",
    "breathing exercises", "guided imagery", "progressive muscle relaxation",
    "autogenic training", "biofeedback", "hypnotherapy", "creative arts therapy",
    "music therapy", "art therapy", "dance therapy", "drama therapy", "play therapy",
    "animal assisted therapy", "nature therapy", "horticulture therapy",
    "ecotherapy", "wilderness therapy", "adventure therapy", "expressive therapy",
    "therapeutic recreation", "recreational therapy", "leisure therapy", "therapeutic exercise",
    "adaptive sports", "adaptive recreation", "inclusive recreation", "universal design",
    "accessibility", "assistive technology", "adaptive technology", "rehabilitation engineering",
    "prosthetics", "orthotics", "mobility aid", "wheelchair", "walker", "cane", "crutches",
    "scooter", "lift chair", "stair lift", "ramps", "grab bars", "bathroom safety",
    "home modification", "vehicle modification", "accessible transportation", "paratransit",
    "community mobility", "independent living", "supported living", "assisted living",
    "nursing home", "long term care", "home health care", "personal care assistant",
    "caregiver support", "respite care", "day care", "adult day care", "senior center",
    "aging in place", "geriatric care management", "elder law", "advance directive",
    "living will", "durable power of attorney", "guardianship", "conservatorship",
    "estate planning", "funeral planning", "bereavement support", "grief counseling",
    "hospice care", "palliative care", "end of life care", "pain management",
    "symptom management", "comfort care", "dignity therapy", "life review", "legacy project",
    "remembrance therapy", "storytelling", "oral history", "life story book", "memory box",
    "scrapbooking", "photo album", "video biography", "audio recording", "memory quilt",
    "memory garden", "memory wall", "memory board", "memory book", "memory jar",
    "memory pillow", "memory bear", "memory bracelet", "memory necklace", "memory ring",
    "memory keychain", "memory ornament", "memory candle", "memory stone", "memory tile",
    "memory plate", "memory frame", "memory book", "memory jar", "memory box",
    "memory tree", "memory wall", "memory board", "memory garden", "memory quilt",
    "memory pillow", "memory bear", "memory bracelet", "memory necklace", "memory ring",
    "memory keychain", "memory ornament", "memory candle", "memory stone", "memory tile",
    "memory plate", "memory frame"
    # Medical Conditions
    "abdominal pain", "abscess", "acne", "acute", "addiction", "ADHD", "allergy", "alopecia",
    "Alzheimer's", "anemia", "aneurysm", "angina", "anorexia", "anxiety", "arthritis",
    "asthma", "atherosclerosis", "autism", "autoimmune", "back pain", "bacterial infection",
    "bipolar disorder", "bladder infection", "bleeding", "blindness", "blood pressure",
    "bone fracture", "brain tumor", "breast cancer", "bronchitis", "burn", "cancer",
    "carpal tunnel", "cataract", "celiac disease", "cerebral palsy", "chickenpox",
    "chlamydia", "cholesterol", "chronic fatigue", "cirrhosis", "colitis", "colon cancer",
    "concussion", "congenital", "COPD", "coronary artery disease", "Crohn's disease",
    "cystic fibrosis", "dandruff", "deafness", "dehydration", "dementia", "depression",
    "dermatitis", "diabetes", "diarrhea", "dizziness", "Down syndrome", "dry eye",
    "dyslexia", "eczema", "edema", "endometriosis", "epilepsy", "erectile dysfunction",
    "fibromyalgia", "flu", "fracture", "gallstones", "gastritis", "GERD", "glaucoma",
    "gout", "hair loss", "headache", "hearing loss", "heart attack", "heart disease",
    "heart failure", "hepatitis", "herpes", "HIV", "hypertension", "hyperthyroidism",
    "hypothyroidism", "IBS", "infection", "infertility", "influenza", "insomnia",
    "iron deficiency", "jaundice", "kidney disease", "kidney stone", "knee pain",
    "lactose intolerance", "liver disease", "lung cancer", "lymphoma", "malaria",
    "measles", "melanoma", "meningitis", "migraine", "miscarriage", "MRSA", "multiple sclerosis",
    "muscle strain", "myocardial infarction", "nausea", "nephritis", "neuropathy",
    "obesity", "osteoporosis", "ovarian cancer", "pancreatitis", "parkinson's disease",
    "PCOS", "peptic ulcer", "pneumonia", "pregnancy", "prostate cancer", "psoriasis",
    "PTSD", "rabies", "rheumatoid arthritis", "rosacea", "schizophrenia", "scoliosis",
    "sepsis", "sinusitis", "skin cancer", "sleep apnea", "STD", "stomach ulcer", "stroke",
    "syphilis", "tendonitis", "testicular cancer", "tuberculosis", "type 1 diabetes",
    "type 2 diabetes", "ulcerative colitis", "UTI", "varicose veins", "vertigo",
    "vitamin deficiency", "vomiting", "warts", "whiplash", "whooping cough", "yeast infection",
    "zika virus",

    # Medications
    "acetaminophen", "acyclovir", "adrenaline", "albuterol", "alprazolam", "amiodarone",
    "amitriptyline", "amlodipine", "amoxicillin", "ampicillin", "anastrozole", "antibiotic",
    "antidepressant", "antihistamine", "aspirin", "atenolol", "atorvastatin", "azithromycin",
    "baclofen", "beclomethasone", "benzodiazepine", "betamethasone", "bisoprolol",
    "budesonide", "buprenorphine", "bupropion", "carbamazepine", "carvedilol", "celecoxib",
    "cephalexin", "ciprofloxacin", "citalopram", "clindamycin", "clonazepam", "clonidine",
    "clopidogrel", "codeine", "colchicine", "cyclobenzaprine", "dexamethasone", "diclofenac",
    "diltiazem", "diphenhydramine", "duloxetine", "enalapril", "epinephrine", "esomeprazole",
    "estradiol", "fentanyl", "fluoxetine", "fluticasone", "furosemide", "gabapentin",
    "gemfibrozil", "glimepiride", "glyburide", "guaifenesin", "haloperidol", "heparin",
    "hydrochlorothiazide", "hydrocodone", "hydroxyzine", "ibuprofen", "insulin", "isosorbide",
    "ketoconazole", "labetalol", "lamotrigine", "lansoprazole", "levetiracetam", "levofloxacin",
    "levothyroxine", "lidocaine", "lisinopril", "loratadine", "lorazepam", "losartan",
    "lovastatin", "meclizine", "meloxicam", "metformin", "methotrexate", "methylprednisolone",
    "metoprolol", "metronidazole", "morphine", "naproxen", "nifedipine", "nitroglycerin",
    "nortriptyline", "olanzapine", "omeprazole", "ondansetron", "oxycodone", "pantoprazole",
    "paroxetine", "penicillin", "phenytoin", "pioglitazone", "pravastatin", "prednisone",
    "propranolol", "quetiapine", "ranitidine", "sertraline", "sildenafil", "simvastatin",
    "spironolactone", "sulfamethoxazole", "sumatriptan", "tadalafil", "tamoxifen",
    "temazepam", "tramadol", "trazodone", "valacyclovir", "valsartan", "venlafaxine",
    "verapamil", "warfarin", "zolpidem",

    # Procedures and Treatments
    "ablation", "amputation", "angiography", "angioplasty", "antibiotic therapy",
    "appendectomy", "arthroscopy", "bariatric surgery", "biopsy", "blood transfusion",
    "bone marrow transplant", "bronchoscopy", "bypass surgery", "cardiac catheterization",
    "carotid endarterectomy", "C-section", "chemotherapy", "cholecystectomy", "colonoscopy",
    "coronary angioplasty", "CT scan", "dialysis", "echocardiogram", "electrocardiogram",
    "electroencephalogram", "endoscopy", "gastrectomy", "gastroscopy", "hemodialysis",
    "hernia repair", "hysterectomy", "immunotherapy", "IVF", "knee replacement",
    "liver transplant", "lumbar puncture", "mammography", "mastectomy", "MRI", "neurosurgery",
    "organ transplant", "pacemaker", "pap smear", "PET scan", "physical therapy", "radiation therapy",
    "renal dialysis", "spinal fusion", "stent placement", "steroids", "thoracotomy",
    "ultrasound", "vaccination", "vasectomy", "x-ray",

    # Specialties
    "allergy and immunology", "anesthesiology", "cardiology", "dermatology", "emergency medicine",
    "endocrinology", "family medicine", "gastroenterology", "geriatrics", "gynecology",
    "hematology", "infectious disease", "internal medicine", "nephrology", "neurology",
    "neurosurgery", "obstetrics", "oncology", "ophthalmology", "orthopedic surgery",
    "otolaryngology", "pediatrics", "plastic surgery", "psychiatry", "pulmonology",
    "radiology", "rheumatology", "urology",

    # Body Systems and Anatomy
    "cardiovascular system", "circulatory system", "digestive system", "endocrine system",
    "immune system", "lymphatic system", "muscular system", "nervous system", "reproductive system",
    "respiratory system", "skeletal system", "skin", "urinary system", "abdomen", "artery",
    "bone", "brain", "colon", "eye", "heart", "intestine", "joint", "kidney", "liver",
    "lung", "muscle", "nerve", "pancreas", "spinal cord", "stomach", "tendon", "thyroid",
    "vein"

    # Medical Conditions
    "abdominal pain", "abscess", "acne", "acute", "addiction", "ADHD", "allergy", "alopecia",
    "Alzheimer's", "anemia", "aneurysm", "angina", "anorexia", "anxiety", "arthritis",
    "asthma", "atherosclerosis", "autism", "autoimmune", "back pain", "bacterial infection",
    "bipolar disorder", "bladder infection", "bleeding", "blindness", "blood pressure",
    "bone fracture", "brain tumor", "breast cancer", "bronchitis", "burn", "cancer",
    "carpal tunnel", "cataract", "celiac disease", "cerebral palsy", "chickenpox",
    "chlamydia", "cholesterol", "chronic fatigue", "cirrhosis", "colitis", "colon cancer",
    "concussion", "congenital", "COPD", "coronary artery disease", "Crohn's disease",
    "cystic fibrosis", "dandruff", "deafness", "dehydration", "dementia", "depression",
    "dermatitis", "diabetes", "diarrhea", "dizziness", "Down syndrome", "dry eye",
    "dyslexia", "eczema", "edema", "endometriosis", "epilepsy", "erectile dysfunction",
    "fibromyalgia", "flu", "fracture", "gallstones", "gastritis", "GERD", "glaucoma",
    "gout", "hair loss", "headache", "hearing loss", "heart attack", "heart disease",
    "heart failure", "hepatitis", "herpes", "HIV", "hypertension", "hyperthyroidism",
    "hypothyroidism", "IBS", "infection", "infertility", "influenza", "insomnia",
    "iron deficiency", "jaundice", "kidney disease", "kidney stone", "knee pain",
    "lactose intolerance", "liver disease", "lung cancer", "lymphoma", "malaria",
    "measles", "melanoma", "meningitis", "migraine", "miscarriage", "MRSA", "multiple sclerosis",
    "muscle strain", "myocardial infarction", "nausea", "nephritis", "neuropathy",
    "obesity", "osteoporosis", "ovarian cancer", "pancreatitis", "parkinson's disease",
    "PCOS", "peptic ulcer", "pneumonia", "pregnancy", "prostate cancer", "psoriasis",
    "PTSD", "rabies", "rheumatoid arthritis", "rosacea", "schizophrenia", "scoliosis",
    "sepsis", "sinusitis", "skin cancer", "sleep apnea", "STD", "stomach ulcer", "stroke",
    "syphilis", "tendonitis", "testicular cancer", "tuberculosis", "type 1 diabetes",
    "type 2 diabetes", "ulcerative colitis", "UTI", "varicose veins", "vertigo",
    "vitamin deficiency", "vomiting", "warts", "whiplash", "whooping cough", "yeast infection",
    "zika virus",

    # Additional Conditions
    "appendicitis", "bursitis", "chronic pain", "COPD", "coronary heart disease", "dyspepsia",
    "fainting", "frostbite", "gas", "glandular fever", "gout", "heat stroke", "Hodgkin's lymphoma",
    "hypoglycemia", "impetigo", "irritable bowel syndrome", "jock itch", "lupus", "malnutrition",
    "menopause", "mumps", "non-Hodgkin's lymphoma", "osteoarthritis", "otitis media", "pelvic inflammatory disease",
    "pneumothorax", "polio", "preeclampsia", "pulmonary embolism", "raynaud's disease", "rotavirus",
    "sciatica", "sickle cell anemia", "sprain", "trichomoniasis", "urethritis", "west nile virus",
    "yellow fever",

    # Medications
    "acetaminophen", "acyclovir", "adrenaline", "albuterol", "alprazolam", "amiodarone",
    "amitriptyline", "amlodipine", "amoxicillin", "ampicillin", "anastrozole", "antibiotic",
    "antidepressant", "antihistamine", "aspirin", "atenolol", "atorvastatin", "azithromycin",
    "baclofen", "beclomethasone", "benzodiazepine", "betamethasone", "bisoprolol",
    "budesonide", "buprenorphine", "bupropion", "carbamazepine", "carvedilol", "celecoxib",
    "cephalexin", "ciprofloxacin", "citalopram", "clindamycin", "clonazepam", "clonidine",
    "clopidogrel", "codeine", "colchicine", "cyclobenzaprine", "dexamethasone", "diclofenac",
    "diltiazem", "diphenhydramine", "duloxetine", "enalapril", "epinephrine", "esomeprazole",
    "estradiol", "fentanyl", "fluoxetine", "fluticasone", "furosemide", "gabapentin",
    "gemfibrozil", "glimepiride", "glyburide", "guaifenesin", "haloperidol", "heparin",
    "hydrochlorothiazide", "hydrocodone", "hydroxyzine", "ibuprofen", "insulin", "isosorbide",
    "ketoconazole", "labetalol", "lamotrigine", "lansoprazole", "levetiracetam", "levofloxacin",
    "levothyroxine", "lidocaine", "lisinopril", "loratadine", "lorazepam", "losartan",
    "lovastatin", "meclizine", "meloxicam", "metformin", "methotrexate", "methylprednisolone",
    "metoprolol", "metronidazole", "morphine", "naproxen", "nifedipine", "nitroglycerin",
    "nortriptyline", "olanzapine", "omeprazole", "ondansetron", "oxycodone", "pantoprazole",
    "paroxetine", "penicillin", "phenytoin", "pioglitazone", "pravastatin", "prednisone",
    "propranolol", "quetiapine", "ranitidine", "sertraline", "sildenafil", "simvastatin",
    "spironolactone", "sulfamethoxazole", "sumatriptan", "tadalafil", "tamoxifen",
    "temazepam", "tramadol", "trazodone", "valacyclovir", "valsartan", "venlafaxine",
    "verapamil", "warfarin", "zolpidem",

    # Additional Medications
    "acetazolamide", "allopurinol", "anastrozole", "aripiprazole", "atomoxetine", "baclofen",
    "benztropine", "betaxolol", "brimonidine", "canagliflozin", "celecoxib", "cetirizine",
    "chlorthalidone", "clobetasol", "clomiphene", "dapsone", "dapoxetine", "darunavir",
    "desloratadine", "dexamethasone", "doxazosin", "doxycycline", "efavirenz", "enoxaparin",
    "famotidine", "felodipine", "finasteride", "fludrocortisone", "fluticasone", "furosemide",
    "gliclazide", "hydroxychloroquine", "irbesartan", "itraconazole", "lamivudine", "letrozole",
    "mefenamic acid", "methimazole", "mirtazapine", "mycophenolate", "nebivolol", "nystatin",
    "olmesartan", "ondansetron", "oseltamivir", "oxcarbazepine", "pemetrexed", "pirfenidone",
    "probenecid", "quinapril", "raltegravir", "ribavirin", "rifampicin", "ritonavir",
    "rosiglitazone", "sertraline", "sevelamer", "sirolimus", "sodium valproate", "tamsulosin",
    "terazosin", "terbinafine", "thyroxine", "tinidazole", "topiramate", "trimethoprim",
    "ursodeoxycholic acid", "vigabatrin", "zidovudine",

    # Procedures
    "ablation", "amputation", "angiography", "angioplasty", "appendectomy", "arthroscopy",
    "bariatric surgery", "biopsy", "blood transfusion", "bypass surgery", "CABG", "cardioversion",
    "carotid endarterectomy", "cataract surgery", "catheterization", "chemotherapy",
    "cholecystectomy", "colonoscopy", "coronary angiography", "CT scan", "dialysis", "echocardiogram",
    "EEG", "EKG", "electrocardiogram", "endoscopy", "gastrectomy", "gastric bypass",
    "gastroscopy", "hemorrhoidectomy", "hysterectomy", "immunotherapy", "incision", "infusion",
    "injection", "IVF", "knee replacement", "laser surgery", "lithotripsy", "lumpectomy",
    "mastectomy", "MRI", "nephrectomy", "neurosurgery", "pacemaker", "palliative care",
    "PET scan", "phlebotomy", "physiotherapy", "radiation therapy", "radiotherapy", "rehabilitation",
    "stenting", "surgery", "thoracotomy", "thyroidectomy", "tracheostomy", "transplant",
    "ultrasound", "vaccination", "vasectomy", "x-ray",

    # Additional Procedures
    "adenoidectomy", "adrenalectomy", "arthroplasty", "balloon sinuplasty", "bone marrow biopsy",
    "bronchoscopy", "carpal tunnel release", "cervical cerclage", "cesarean section", "cystoscopy",
    "defibrillation", "fetal surgery", "fundoplication", "gastroscopy", "glucose tolerance test",
    "heart transplantation", "hernioplasty", "hydrocele repair", "intrauterine device insertion",
    "laparoscopy", "LASIK", "liver biopsy", "lobectomy", "loop electrosurgical excision procedure",
    "lumbar puncture", "mammography", "meniscectomy", "myomectomy", "orchiectomy",
    "pancreaticoduodenectomy", "paracentesis", "pericardiocentesis", "pessary insertion",
    "pleurodesis", "pneumonectomy", "prostate biopsy", "radiographic imaging", "sigmoidoscopy",
    "spirometry", "splenectomy", "stereotactic radiosurgery", "thyroid biopsy", "tonsillectomy",
    "trigger point injection", "tubal ligation", "ureteroscopy", "vitrectomy",

    # Treatments
    "acupuncture", "antibiotic therapy", "antiviral therapy", "behavioral therapy",
    "chemotherapy", "cognitive therapy", "counseling", "CPAP", "dialysis", "gene therapy",
    "hormone therapy", "hypnosis", "immunotherapy", "massage therapy", "occupational therapy",
    "physical therapy", "psychotherapy", "radiation therapy", "stem cell therapy", "surgery",
    "vaccination", "speech therapy", "oxygen therapy", "light therapy", "detoxification",

    # Additional Treatments
    "aerobic exercise", "biofeedback", "chiropractic", "cryotherapy", "dialectical behavior therapy",
    "electroconvulsive therapy", "exposure therapy", "family therapy", "hydrotherapy",
    "ketogenic diet", "manual therapy", "neurofeedback", "occupational therapy", "orthotics",
    "pilates", "pneumatic compression", "proton therapy", "pulmonary rehabilitation",
    "reflexology", "support groups", "tai chi", "yoga", "zen meditation", "mindfulness meditation",
    "craniosacral therapy",

    # Specialties
    "allergy", "anesthesiology", "cardiology", "dermatology", "emergency medicine", "endocrinology",
    "ENT", "epidemiology", "family medicine", "gastroenterology", "geriatrics", "hematology",
    "immunology", "infectious disease", "internal medicine", "nephrology", "neurology",
    "neurosurgery", "OB/GYN", "oncology", "ophthalmology", "orthopedics", "pediatrics",
    "plastic surgery", "psychiatry", "pulmonology", "radiology", "rheumatology", "urology",
    "vascular surgery",

    # Additional Specialties
    "adolescent medicine", "allergy and immunology", "clinical genetics", "clinical pharmacology",
    "critical care medicine", "developmental-behavioral pediatrics", "emergency medical services",
    "forensic pathology", "hospice and palliative medicine", "infectious diseases",
    "interventional cardiology", "lifestyle medicine", "medical genetics", "medical toxicology",
    "neonatology", "neurodevelopmental disabilities", "nuclear medicine", "occupational medicine",
    "pain medicine", "pediatric cardiology", "pediatric endocrinology", "pediatric gastroenterology",
    "pediatric hematology-oncology", "pediatric nephrology", "pediatric pulmonology",
    "pediatric rheumatology", "preventive medicine", "reproductive endocrinology and infertility",
    "sleep medicine", "sports medicine", "transplant hepatology", "vascular medicine",

    # Body Systems
    "cardiovascular", "digestive", "endocrine", "immune", "integumentary", "lymphatic",
    "musculoskeletal", "nervous", "reproductive", "respiratory", "skeletal", "urinary",
    "circulatory", "excretory", "gastrointestinal", "genitourinary", "ocular", "renal",
    "sensory", "integumentary system", "reproductive system", "muscular system",

    # Additional Body Systems
    "auditory system", "cellular system", "hormonal system", "lymphatic system",
    "neurological system", "peripheral nervous system", "sympathetic nervous system",
    "parasympathetic nervous system", "vestibular system", "autonomic nervous system",
    "central nervous system", "vascular system", "integumentary system", "gastrointestinal system",

    # Miscellaneous
    "abdomen", "artery", "bacteria", "bladder", "blood", "bone", "brain", "breast", "cell",
    "cervix", "colon", "diagnosis", "gene", "gland", "hormone", "immune system", "infection",
    "inflammation", "joint", "kidney", "liver", "lung", "lymph node", "medication", "muscle",
    "nerve", "organ", "pancreas", "pelvis", "prostate", "radiation", "spleen", "stomach",
    "surgery", "symptom", "tissue", "tumor", "ulcer", "urine", "vaccine", "vein", "virus",

    # Additional Miscellaneous
    "abdomen", "acid", "adrenal", "airway", "alveoli", "antibody", "aorta", "appendix",
    "areola", "atrium", "axilla", "bile", "bilirubin", "bronchi", "capillary", "carcinogen",
    "carpus", "cartilage", "clavicle", "coccyx", "cornea", "cutaneous", "diaphragm", "duodenum",
    "epidermis", "esophagus", "femur", "fibula", "follicle", "gallbladder", "glucose", "humerus",
    "ileum", "ilium", "incisor", "ischium", "jejunum", "ligament", "lumbar", "mandible",
    "maxilla", "meniscus", "metacarpus", "metatarsus", "mucus", "nasal", "neuron", "oculus",
    "oesophagus", "patella", "pectoral", "pericardium", "pharynx", "photon", "plasma", "platelet",
    "pupil", "radius", "rectum", "retina", "rib", "sacrum", "scapula", "serum", "sphincter",
    "sternum", "synapse", "synovial", "tarsus", "tendon", "thorax", "thyroid", "trachea",
    "ulna", "uterus", "vertebra", "vitamin","glioma"

]
print(len(medical_keywords))

